### ISSUE TITLE
Commit id of scanner / compatibility issue

### ISSUE THREAD

**Issue by msharmavikram** [scanner-research/scannertools#1]
Hi there! 
I tried using scannertools on top of the tree of scannerresearch. 
I see that the scannertools expect some older commit ids. 

For example,  scannertool still uses sampler in database to perform some gathering. However, top of the tree does not have sampler module anymore. 

Could you please suggest correct commit id to use the scannertools?

**Comment by willcrichton** [comment]
This has been fixed. Repository tags (and subsequently pip versions) should match compatibility with Scanner.
