### ISSUE TITLE
scannertools_sql: warning: manifest_maker: standard file '-c' not found

### ISSUE THREAD

**Issue by mamo0202** [scanner-research/scannertools#12]
After installing scannertools_infra, scannertools and scannertools_caffe.
when i installed scannertools_sql and  printed out an extremely long error message.
I searched for the bug from the Error and I've made it bold.
Do you know how to solve it?

Error:
Installing collected packages: scannertools-sql
  Found existing installation: scannertools-sql 0.2.15
    Can't uninstall 'scannertools-sql'. No files were found to uninstall.
  Running setup.py develop for scannertools-sql
    ERROR: Complete output from command /usr/bin/python3 -c 'import setuptools, tokenize;__file__='"'"'/home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=:
    **ERROR: running develop**
    running egg_info
    writing top-level names to scannertools_sql.egg-info/top_level.txt
    writing scannertools_sql.egg-info/PKG-INFO
    writing dependency_links to scannertools_sql.egg-info/dependency_links.txt
    **warning: manifest_maker: standard file '-c' not found**
    
    reading manifest file 'scannertools_sql.egg-info/SOURCES.txt'
    writing manifest file 'scannertools_sql.egg-info/SOURCES.txt'
    running build_ext
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Performing Test COMPILER_SUPPORTS_CXX1Y
    -- Performing Test COMPILER_SUPPORTS_CXX1Y - Success
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Found Protobuf: /home/wcj/scanner/scanner/thirdparty/install/lib/libprotobuf.so
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
    -- Checking for module 'libpqxx'
    --   Found libpqxx, version 4.0
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/build/temp.linux-x86_64-3.5
    Scanning dependencies of target scannertools_sql_proto_files
    [ 25%] Running C++ protocol buffer compiler on scannertools_sql.proto
    [ 25%] Running Python protocol buffer compiler on scannertools_sql.proto
    [ 25%] Built target scannertools_sql_proto_files
    Scanning dependencies of target scannertools_sql
    [ 37%] Building CXX object CMakeFiles/scannertools_sql.dir/sql_source.cpp.o
    [ 50%] Building CXX object CMakeFiles/scannertools_sql.dir/scannertools_sql.pb.cc.o
    [ 62%] Building CXX object CMakeFiles/scannertools_sql.dir/sql.cpp.o
    [ 75%] Building CXX object CMakeFiles/scannertools_sql.dir/sql_sink.cpp.o
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp: In member function ‘virtual scanner::i64 scanner::SQLEnumerator::total_elements()’:
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:55:11: error: ‘row’ is not a member of ‘pqxx’
               pqxx::row r = txn.exec1(query_str);
               ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:56:36: error: ‘r’ was not declared in this scope
               total_elements_cached_ = r[0].as<i32>();
                                        ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:56:47: error: expected primary-expression before ‘>’ token
               total_elements_cached_ = r[0].as<i32>();
                                                   ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:56:49: error: expected primary-expression before ‘)’ token
               total_elements_cached_ = r[0].as<i32>();
                                                     ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp: At global scope:
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:191:26: error: ‘pqxx::row’ has not been declared
       json row_to_json(pqxx::row row) {
                              ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:236:27: error: ‘row’ is not a member of ‘pqxx’
       std::vector<std::vector<pqxx::row>> cached_rows_;
                               ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:236:27: error: ‘row’ is not a member of ‘pqxx’
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:236:33: error: template argument 1 is invalid
       std::vector<std::vector<pqxx::row>> cached_rows_;
                                     ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:236:33: error: template argument 2 is invalid
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:236:36: error: template argument 1 is invalid
       std::vector<std::vector<pqxx::row>> cached_rows_;
                                        ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:236:36: error: template argument 2 is invalid
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp: In member function ‘virtual void scanner::SQLSource::read(const std::vector<scanner::ElementArgs>&, std::vector<std::vector<scanner::Element> >&)’:
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:144:22: error: request for member ‘clear’ in ‘((scanner::SQLSource*)this)->scanner::SQLSource::cached_rows_’, which is of non-class type ‘int’
             cached_rows_.clear();
                          ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:145:21: error: ‘row’ is not a member of ‘pqxx’
             std::vector<pqxx::row> cur_group;
                         ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:145:21: error: ‘row’ is not a member of ‘pqxx’
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:145:30: error: template argument 1 is invalid
             std::vector<pqxx::row> cur_group;
                                  ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:145:30: error: template argument 2 is invalid
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:151:26: error: request for member ‘push_back’ in ‘((scanner::SQLSource*)this)->scanner::SQLSource::cached_rows_’, which is of non-class type ‘int’
                 cached_rows_.push_back(cur_group);
                              ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:152:37: error: ‘row’ is not a member of ‘pqxx’
                 cur_group = std::vector<pqxx::row>();
                                         ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:152:37: error: ‘row’ is not a member of ‘pqxx’
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:152:46: error: template argument 1 is invalid
                 cur_group = std::vector<pqxx::row>();
                                                  ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:152:46: error: template argument 2 is invalid
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:154:21: error: request for member ‘push_back’ in ‘cur_group’, which is of non-class type ‘int’
               cur_group.push_back(row);
                         ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:157:22: error: request for member ‘push_back’ in ‘((scanner::SQLSource*)this)->scanner::SQLSource::cached_rows_’, which is of non-class type ‘int’
             cached_rows_.push_back(cur_group);
                          ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:170:44: error: invalid types ‘int[long int]’ for array subscript
           auto& row_group = cached_rows_[row_id];
                                                ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:171:23: error: unable to deduce ‘auto&&’ from ‘row_group’
           for (auto row : row_group) {
                           ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp: In member function ‘nlohmann::json scanner::SQLSource::row_to_json(int)’:
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:195:32: error: ‘begin’ was not declared in this scope
           for (pqxx::field field : row) {
                                    ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:195:32: note: suggested alternative:
    In file included from /usr/local/lib/python3.5/dist-packages/scannerpy/include/scanner/util/json.hpp:920:0,
                     from /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:21:
    /usr/include/c++/5/valarray:1206:5: note:   ‘std::begin’
         begin(const valarray<_Tp>& __va)
         ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:195:32: error: ‘end’ was not declared in this scope
           for (pqxx::field field : row) {
                                    ^
    /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:195:32: note: suggested alternative:
    In file included from /usr/local/lib/python3.5/dist-packages/scannerpy/include/scanner/util/json.hpp:920:0,
                     from /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/scannertools_sql_cpp/sql_source.cpp:21:
    /usr/include/c++/5/valarray:1226:5: note:   ‘std::end’
         end(const valarray<_Tp>& __va)
         ^
    CMakeFiles/scannertools_sql.dir/build.make:118: recipe for target 'CMakeFiles/scannertools_sql.dir/sql_source.cpp.o' failed
    make[2]: *** [CMakeFiles/scannertools_sql.dir/sql_source.cpp.o] Error 1
    make[2]: *** 正在等待未完成的任务....
    CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/scannertools_sql.dir/all' failed
    make[1]: *** [CMakeFiles/scannertools_sql.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/setup.py", line 23, in <module>
        zip_safe=False)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/wcj/scanner/scannertools/scannertools_infra/scannertools_infra/__init__.py", line 28, in run
        super().run()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 119, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/wcj/scanner/scannertools/scannertools_infra/scannertools_infra/__init__.py", line 57, in run
        self.build_extension(ext)
      File "/home/wcj/scanner/scannertools/scannertools_infra/scannertools_infra/__init__.py", line 85, in build_extension
        cwd=self.build_temp)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'RelWithDebugInfo', '--', '-j4']' returned non-zero exit status 2
    ----------------------------------------
  ERROR: Can't roll back scannertools-sql; was not uninstalled
ERROR: Command "/usr/bin/python3 -c 'import setuptools, tokenize;__file__='"'"'/home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=" failed with error code 1 in /home/wcj/scanner/code/scanner_latest/scannertools/scannertools_sql/

**Comment by willcrichton** [comment]
I think your libpqxx version is out of date. The version in our builds is 6.2.2, and yours is 4.0. I would install a more recent version.

**Comment by mamo0202** [comment]
Ok，thanks！
