### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by seahyinghang8** [scanner-research/scannertools#6]
scannertools require opencv-python and scipy to work. A requirements.txt should be added

**Comment by willcrichton** [comment]
For Python package (as opposed to applications), we have dependencies registered in `setup.py`. Unfortunately there's no way to install OpenCV through `pip`, so we just have to list that as a dependency in the README. However scipy should be added. Can you submit a patch to add that?

**Comment by seahyinghang8** [comment]
To clarify, I will add this to the setup.py for scannertools/scannertools/setup.py? I think opencv is installed using the bash script in scanner but the python bindings for opencv-python has to be installed with pip. So I think that has to be added too?

**Comment by willcrichton** [comment]
Just add scipy. We'll ignore opencv for now because OpenCV python cannot be installed through pip.

**Comment by seahyinghang8** [comment]
Oh. I installed scanner from source, which already installed opencv. However, when I imported scannertools on python, it complained that it could not import cv2. As a result, I ran `pip install --user opencv-python` and then it worked...

**Comment by seahyinghang8** [comment]
Oh i just read the readme about how I should have ran `sudo apt install

**Comment by willcrichton** [comment]
When you install Scanner from source, at the bottom of the `deps.sh` output it lists a series of commands you're supposed to add to your bashrc. That will include a PYTHONPATH that will provide OpenCV.

**Comment by seahyinghang8** [comment]
Got it. I think I might have added the PYTHONPATH but did run the bash file.
