### ISSUE TITLE
tensorflow, align, pandas, nltk, gensim dependencies needed

### ISSUE THREAD

**Issue by seahyinghang8** [scanner-research/scannertools#7]
scannertools import the above packages but they are not included in setup.py

**Comment by willcrichton** [comment]
Where are you finding nltk and gensim? Those shouldn't be in this repo.

**Comment by seahyinghang8** [comment]
Those were the dependencies that caused my program to crash when I followed the tutorial on http://scanner.run/api/scannertools.html. It always states that there is an import error, and thus, I assumed that it was the problem.

**Comment by willcrichton** [comment]
Can you paste the full trace, i.e. where those dependencies were getting imported from?

**Comment by seahyinghang8** [comment]
I believe the imports came from the wrong align package. I have corrected it and it is working fine now. Thank you!
