### ISSUE TITLE
ImportError: No module named 'align.detect_face'

### ISSUE THREAD

**Issue by seahyinghang8** [scanner-research/scannertools#8]
The package is imported in scannertools/face_detection.py. Is the align package not the one on pip but the one in facenet?

**Comment by willcrichton** [comment]
That's right. For now you need to clone the repo and add `facenet/src` to your PYTHONPATH.

**Comment by seahyinghang8** [comment]
Should I add this instruction to the readme.md?

**Comment by willcrichton** [comment]
Go for it!

**Comment by 15520533** [comment]
hello, did you fix this, i got this problem too, i'm import align.detect_face, but it keep saying: "No module named align.detect_face while this py file is actually in my /home/pi/FaceRecog/src/align/detect_face.py

**Comment by seahyinghang8** [comment]
During the time that I was working on this project, I had to clone facenet separately. However, the version of facenet might have changed, and the dependency might have been broken.
